TiendaMascotas/TiendaMascotas/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TiendaMascotas.Entities;
using TiendaMascotas.Models;

namespace TiendaMascotas.Controllers
{
    //[FiltroPersonalizadoSesion]
    public class PagosController : Controller
    {
        PagosModel pagosModel = new PagosModel();
        ProductosModel productosModel = new ProductosModel();
        LogsModel LogsModel = new LogsModel();
        ProductosModel model2 = new ProductosModel();

        [HttpPost]
        public ActionResult ConfirmarPago()
        {
            try
            {
                
                if (pagosModel.ValidarStock() == 1)
                {
                    pagosModel.ConfirmarPago();

                    var Temporal = productosModel.MostrarCompraCarrito();
                    Session["CantidadCompra"] = Temporal.CantidadCompra;
                    Session["MontoCompra"] = Temporal.MontoCompra;

                    return Json("Ok", JsonRequestBehavior.AllowGet);
                    
                }
                else
                {
                    throw new Exception("Hay un producto en el carrito que ya no se encuentra disponible.");
                }

            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                Session["ErrorMessage"] = "Error al pagar: " + ex.Message;
                return RedirectToAction("ProductoCarrito", "Productos");
            }
        }


        [HttpGet]
        public ActionResult MostrarFacturas()
        {
            try
            {
                var datos = pagosModel.MostrarFacturas();
                return View(datos);
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }
        }

        public void RegistrarLog(Exception ex)
        {
            LogsEnt log = new LogsEnt();
            log.origen = ControllerContext.RouteData.Values["controller"].ToString() + "-" + ControllerContext.RouteData.Values["action"].ToString();
            log.mensajeError = ex.Message;
            LogsModel.RegistrarBitacora(log);
        }


    }
}

TiendaMascotas/TiendaMascotas/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiendaMascotas.App_Start;
using TiendaMascotas.Entities;
using TiendaMascotas.Models;

namespace TiendaMascotas.Controllers
{
    public class ProductosController : Controller
    {

        ProductosModel model = new ProductosModel();
        LogsModel LogsModel = new LogsModel();

        [HttpGet]
        public ActionResult ProductosVenta()
        {
            try
            {

                // Check if Session["Consecutivo"] has a value
                if (Session["Consecutivo"] != null)
                {
                    var Temporal = model.MostrarCompraCarrito();
                    Session["CantidadCompra"] = Temporal.CantidadCompra;
                    Session["MontoCompra"] = Temporal.MontoCompra;
                }

                var resultado = model.MostrarProductos();
                return View(resultado);
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }

        }
        [HttpGet]
        //[FiltroSesion]
        public ActionResult RegistrarProducto()
        {
            try
            {
                ViewBag.ListadoProductos = model.MostrarProductos();// antes era: ViewBag.ListadoProductos = model.ConsultarProducto();
                return View();
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }
        }

        [HttpPost]
        //[FiltroSesion]
        public ActionResult RegistrarProducto([Bind(Include = "nombre, descripcion,cantidad,precio")] ProductoEnt entidad, HttpPostedFileBase imagen1)
        {
            try
            {

                entidad.imagen = new byte[imagen1.ContentLength];
                imagen1.InputStream.Read(entidad.imagen, 0 , imagen1.ContentLength);

                if (model.RegistrarProducto(entidad) > 0)
                {
                    var resultado = model.MostrarProductos();
                    return View("ProductosVenta", resultado);
                }
                else
                {
                    ViewBag.mensaje = "Los datos no se validaron";
                    return View();
                }
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }
        }

        [HttpPost]
        //[FiltroSesion]
        //Parte 1 - Con AJAX, se llama desde ~/assets/jsProductos/productos.js que eventualmente se llama desde la vista ProductosVenta.cshtml en el Eliminar
        //Parte 2 - Una vez se recibe respuesta del API/ProductosModel/EliminarProducto se dice que se eliminó correctamente (devuelve 'Ok')
        public ActionResult EliminarProducto(int id)
        {
            model.EliminarProducto(id);
            return Json("Ok", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [FiltroSesion]
        public ActionResult FormProductos()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }
        }

  
        [HttpGet]
        //[FiltroSesion]
        public ActionResult ActualizarProducto(int q)
        {
            try
            {
                var resultado = model.ConsultarProducto(q);
                ViewBag.ListadoAnimales = model.MostrarProductos();
                return View(resultado);
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }
        }

        [HttpPost]
        //[FiltroSesion]
        public ActionResult ActualizarProducto(ProductoEnt entidad)
        {
            try
            {
                model.ActualizarProducto(entidad);
                return RedirectToAction("ProductosVenta", "Productos");
            }
            catch (Exception ex)
            {
                RegistrarLog(ex);
                return View();
            }
        }


        //Metodo registrar bitacora
        public void RegistrarLog(Exception ex)
        {
            LogsEnt log = new LogsEnt();
            log.origen = ControllerContext.RouteData.Values["controller"].ToString()
                + "-" + ControllerContext.RouteData.Values["action"].ToString();
            log.mensajeError = ex.Message;
            LogsModel.RegistrarBitacora(log);
        }


        [HttpPost]
        public ActionResult ActualizarCarrito(int idProducto, int cantidad)
        {
            model.ActualizarCarrito(idProducto, cantidad);
            return Json("Ok", JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ProductoCarrito()
        {
            var Datos = model.MostrarDetalleCarrito();
            ViewBag.Totalizador = Datos.Sum(x => x.Total);

            return View(Datos);
        }



    }
}

TiendaMascotas/TiendaMascotas/Views/Productos/ActualizarProducto.cshtml
@model TiendaMascotas.Entities.ProductoEnt
@{
    ViewBag.Title = "ActualizarProducto";
    Layout = "~/Views/Shared/LayoutProducts.cshtml";
}


<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>Actualizando</p>
                    <h1>Producto</h1>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="product-section mt-100 mb-150">
    <div class="container">

        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">

                <h2>Ingrese los datos nuevos que desea actualizar</h2>
                <br>
                <br>

                @using (Html.BeginForm("ActualizarProducto", "Productos", FormMethod.Post, new { @class = "pt-3" }))
                {

                    @Html.HiddenFor(Model => Model.idProducto)

                    <!-- corregir diseño inputs, seguir trabajando en crud-->
                    <div class="form-group col-lg-8 offset-lg-2 text-center">
                        @Html.TextBoxFor(Model => Model.nombre, new
                   {
                       @class = "form-control form-control-lg",
                       @placeholder = "Nombre del producto",
                       @autocomplete = "Off",
                       @required = true
                   })
                    </div>

                    <br>
                    <div class="form-group col-lg-8 offset-lg-2 text-center">
                        @Html.TextBoxFor(Model => Model.descripcion, new
                   {
                       @class = "form-control form-control-lg",
                       @placeholder = "Descripcion",
                       @autocomplete = "Off",
                       @required = true
                   })
                    </div>

                    <br>
                    <div class="form-group col-lg-8 offset-lg-2 text-center">
                        @Html.TextBoxFor(Model => Model.cantidad, new
                   {
                       @class = "form-control form-control-lg",
                       @placeholder = "Cantidad",
                       @autocomplete = "Off",
                       @required = true
                   })
                    </div>

                    <br>
                    <div class="form-group col-lg-8 offset-lg-2 text-center">
                        @Html.TextBoxFor(Model => Model.precio, new
                   {
                       @class = "form-control form-control-lg",
                       @placeholder = "Precio",
                       @autocomplete = "Off",
                       @required = true
                   })
                    </div>

                    <br>
                    <br>

                    <br>
                   
                    <br>
                    <div class="mt-3">

                        <br>
                        <br>
                        <div class="row">
                            <div class="col-lg-8 offset-lg-2 text-center">
                                <input type="submit" id="btnRegistrar" value="Registrar" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">
                            </div>
                        </div>

                    </div>

                }
            </div>
        </div>

    </div>
</div>

TiendaMascotas/TiendaMascotas/Views/Productos/ProductoCarrito.cshtml
@model IEnumerable<TiendaMascotas.Entities.DetalleComprasEnt>
@{
    ViewBag.Title = "ProductoCarrito";
    Layout = "~/Views/Shared/LayoutProducts.cshtml";
}

<link href="~/assets/css/productos.css" rel="stylesheet" type="text/css" />

<!-- end header -->
<!-- search area -->
<div class="search-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <span class="close-btn"><i class="fas fa-window-close"></i></span>
                <div class="search-bar">
                    <div class="search-bar-tablecell">
                        <h3>Buscar:</h3>
                        <input type="text" placeholder="Escriba palabras claves">
                        <button type="submit">Buscar <i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end search arewa -->
<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <h1>Carrito de Compra</h1>
                </div>
                
                <div>
            </div>
        </div>
    </div>
</div>


<!-- end breadcrumb section -->

    <div class="row">

        <div class="col-md-1 grid-margin stretch-card">
        </div>

        <div class="col-md-10 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Detalle a pagar</h4>

                    <table class="table table-hover" id="tablaDetalleCarrito">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                                <th>¢ Precio</th>
                                <th>¢ Sub Total</th>
                                <th>¢ Impuesto</th>
                                <th>¢ Total</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Nombre</td>
                                    <td>@item.Cantidad</td>
                                    <td>@string.Format("{0:n2}", @item.Precio)</td>
                                    <td>@string.Format("{0:n2}", @item.SubTotal)</td>
                                    <td>@string.Format("{0:n2}", @item.Impuesto)</td>
                                    <td>@string.Format("{0:n2}", @item.Total)</td>
                                </tr>
                            }

                        </tbody>
                    </table>

                    <br />
                    <br />
                    @using (Html.BeginForm("", "", FormMethod.Post))
                    {
                        var x = string.Format("{0:n2}", @ViewBag.Totalizador);
                        <Label style="color: black;">Total a pagar: </Label> <span style="color: black;">¢@x</span>;




                    }
                    <a class="cart-btn product-btn" onclick="Pagando()"> Realizar Pago</a>








                </div>
                <div>
                    <a class="btn btn-outline-primary btn-sm" href="@Url.Action("MostrarFacturas", "Pagos")">Ver Historial de Facturas</a>
                </div>
            </div>
        </div>

    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    function checkTableIsEmpty() {
        var table = document.getElementById("tablaDetalleCarrito");
        var tbody = table.getElementsByTagName("tbody")[0];
        if (tbody.children.length === 0) {
            document.querySelector(".cart-btn").style.display = "none";
        }
    }



    window.onload = checkTableIsEmpty;

    $(document).ready(function () {
        $('#tablaDetalleCarrito').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
            }
        });
    });

    function RecargarPantalla() {
        window.location.href = "/Productos/ProductoCarrito";
    }

    function RecargarPantalla2() {
        window.location.href = "/Pagos/MostrarFacturas";
    }


    function Pagando() {

            $.ajax({
                type: "POST",
                url: "/Pagos/ConfirmarPago",
                dataType: "json",
                success: function (res) {
                    Swal.fire({
                        position: 'top-center',
                        icon: 'success',
                        title: 'Pago efectuado exitosamente',
                        showConfirmButton: false,
                        timer: 2000
                    })

                    setTimeout(function () {
                        RecargarPantalla2();
                    }, 2200);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    Swal.fire({
                            position: 'top-center',
                            icon: 'error',
                            title: 'Error al ejecutar el pago del carrito',
                            text: '@TempData["ErrorMessage"]',
                            showConfirmButton: false,
                            timer: 2000
                        })
                }
            });

        

    }
</script> 

TiendaMascotas/TiendaMascotas/Views/Productos/ProductosVenta.cshtml
@model IEnumerable<TiendaMascotas.Entities.ProductoEnt>
@{
    ViewBag.Title = "ProductosVenta";
    Layout = "~/Views/Shared/LayoutProducts.cshtml";
}


<link href="~/assets/css/productos.css" rel="stylesheet" type="text/css" />

<!-- end header -->
<!-- search area -->
<div class="search-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <span class="close-btn"><i class="fas fa-window-close"></i></span>
                <div class="search-bar">
                    <div class="search-bar-tablecell">
                        <h3>Buscar:</h3>
                        <input type="text" placeholder="Escriba palabras claves">
                        <button type="submit">Buscar <i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end search arewa -->
<!-- breadcrumb-section -->
<div class="breadcrumb-section breadcrumb-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 text-center">
                <div class="breadcrumb-text">
                    <p>Bienvenido/a a nuestra gran variedad de</p>
                    <h1>Productos</h1>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- end breadcrumb section -->
<!-- products -->

<div class="product-section mt-50 mb-150">

    @if (Session["rol"] != null)
    {
        if (Convert.ToInt32(Session["rol"].ToString()) == 1)
        {
            <li class="col-lg-12 col-md-6 text-center strawberry">
                <h3>Registrar Productos</h3>
                <a href="@Url.Action("RegistrarProducto", "Productos")">¡Haz click aquí para registrar un producto!</a>
            </li>
        }
    }

    <br>
    <br>
    <br>
    <br>
    <h1 class="col-lg-12 col-md-6 text-center strawberry">
        Lista de productos en nuestra tienda:
    </h1>
    <br>
    <br>
    <br>
    <div class="container">

        <div class="row product-lists">

            @if (Session["rol"] == null)
            {

                foreach (var item in Model)
                {

                    <div class="col-lg-4 col-md-6 text-center strawberry">
                        <div class="single-product-item">
                            <div class="product-image">
                                @{
                                    var base64 = Convert.ToBase64String(item.imagen);
                                    var imagensrc = string.Format("data:image/gif;base64,{0}", base64);
                                }
                                @*<a href="cart.html"><img src="~/assets/imgperros/Ruffos.jpg" alt=""></a>*@
                                <img src="@imagensrc" style="max-height: 1200px; max-width: 900px" />
                            </div>

                            <h1>@item.nombre</h1>
                            <h5>Descripcion: @item.descripcion</h5>
                            <h5>Cantidad: @item.cantidad</h5>
                            <h5>Precio: @item.precio</h5>

                         
                        </div>
                    </div>



                }
            }
            else if (Convert.ToInt32(Session["rol"].ToString()) == 1)
            {
                foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 text-center strawberry">
                        <div class="single-product-item">
                            <div class="product-image">
                                @{
                                    var base64 = Convert.ToBase64String(item.imagen);
                                    var imagensrc = string.Format("data:image/gif;base64,{0}", base64);
                                }
                                @*<a href="cart.html"><img src="~/assets/imgperros/Ruffos.jpg" alt=""></a>*@
                                <img src="@imagensrc" style="max-height: 1200px; max-width: 900px" />
                            </div>

                            <h1>@item.nombre</h1>
                            <h5>Descripcion: @item.descripcion</h5>
                            <h5>Cantidad: @item.cantidad</h5>
                            <h5>Precio: @item.precio</h5>



                            <br>
                            <br />
                            <a class="cart-btn product-btn" href="@Url.Action("ActualizarProducto", "Productos", new { q = item.idProducto })"><img src="~/assets/imgs/form.png" alt="">Actualizar</a>
                            <br>
                            <br />
                            <a class="cart-btn product-btn openModal" data-toggle="modal" data-target="#exampleModalCenter" href="#" data-backdrop="static" data-keyboard="false" data-id=@item.idProducto><img src="~/assets/imgs/trash-can.png" alt="">Eliminar Producto</a>
                            <br>
                            <br />
                            <a class="cart-btn product-btn" onclick="ActualizarCarrito(@item.idProducto, @item.cantidad)"><img src="~/assets/imgs/carshop.png" alt=""> Agregar a Carrito</a>
                            <br>
                            <br />

                            <br>   <br />

                            <label for="quantity">Cantidad:</label>
                            <input type="number" id="carrito-@item.idProducto" name="quantity" min="1" max="10" value="1">
                            <br>
                            <br />


                        </div>
                    </div>

                }


            }

            else if (Convert.ToInt32(Session["rol"].ToString()) == 2)
            {
                foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 text-center strawberry">
                        <div class="single-product-item">
                            <div class="product-image">
                                @{
                                    var base64 = Convert.ToBase64String(item.imagen);
                                    var imagensrc = string.Format("data:image/gif;base64,{0}", base64);
                                }
                                @*<a href="cart.html"><img src="~/assets/imgperros/Ruffos.jpg" alt=""></a>*@
                                <img src="@imagensrc" style="max-height: 1200px; max-width: 900px" />
                            </div>

                            <h1>@item.nombre</h1>
                            <h5>Descripcion: @item.descripcion</h5>
                            <h5>Cantidad: @item.cantidad</h5>
                            <h5>Precio: @item.precio</h5>


                            <br>
                            <br />
                            <a class="cart-btn product-btn" onclick="ActualizarCarrito(@item.idProducto, @item.cantidad)"><img src="~/assets/imgs/carshop.png" alt=""> Agregar a Carrito</a>


                            <br>   <br />

                            <label for="quantity">Cantidad:</label>
                            <input type="number" id="carrito-@item.idProducto" name="quantity" min="1" max="10" value="1">
                            <br>
                            <br />


                        </div>
                    </div>

                }


            }

        </div>
    </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Eliminar Producto</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="color: black;">
                ¿Desea eliminar el Producto?
                <input type="hidden" id="idModalHidden">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="EliminarProducto();">Sí, quiero eliminar el producto</button>
            </div>
        </div>
    </div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="~/assets/jsProductos/productos.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>

    function RecargarPantalla() {
        window.location.href = "/Productos/ProductosVenta";
    }

    function ActualizarCarrito(idProducto, cantidad) {

        let CantidadCarrito = $("#carrito-" + idProducto).val();

        if (CantidadCarrito > cantidad) {

            Swal.fire({
                position: 'top-center',
                icon: 'warning',
                title: '¡La cantidad de producto seleccionada excede disponibilidad en inventario!',
                showConfirmButton: false,
                timer: 2000
            })
        }
        else {
            
            $.ajax({
                type: "POST",
                url: "/Productos/ActualizarCarrito",
                dataType: "json",
                data: {
                    "idProducto": idProducto,
                    "cantidad": CantidadCarrito // pass the CantidadCarrito variable as the 'cantidad' parameter
                },
                success: function (res) {
                    Swal.fire({
                        position: 'top-center',
                        icon: 'success',
                        title: 'Producto agregado a carrito',
                        showConfirmButton: false,
                        timer: 2000
                    })

                    setTimeout(function () {
                        RecargarPantalla();
                    }, 2200);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    Swal.fire({
                        position: 'top-center',
                        icon: 'error',
                        title: 'Error al agregar producto al carrito',
                        text: 'Error: ' + textStatus + ' ' + errorThrown,
                        showConfirmButton: false,
                        timer: 2000
                    })
                }
            });

        }

    }

</script>